version: "3.3"
services:
  php:
    build:
        context: ./docker/php
    ports:
        - 9000:9000
    volumes:
        - ./Site:/srv/www/fumesoft
        - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    image: nginx:1.13.8
    ports:
        - 8081:80
    volumes:
        - ./Site:/srv/www/fumesoft
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8', 
    '--collation-server=utf8_general_ci',
    '--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf

      

