version: "3.3"
services:
  apache:
    build: 
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    volumes:
      - ./docker/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf


